### ISSUE TITLE
Tic-Tac-Toe using Javascript

### ISSUE THREAD

**Issue by PravinPadalkar78** [codersalman/Hacktoberfest-2022#40]
Please assign this issue to me with hacktober lables . Thank You..

**Comment by 035pratheeksha** [comment]
Could you please assign this to me? @PravinPadalkar78

**Comment by codersalman** [comment]
> Could you please assign this to me? @PravinPadalkar78

create new and diffrent

**Comment by 035pratheeksha** [comment]
> > Could you please assign this to me? @PravinPadalkar78
> 
> create new and diffrent

Yeah new code for tic tac toe using java ryt?

**Comment by codersalman** [comment]
> > > Could you please assign this to me? @PravinPadalkar78
> > 
> > 
> > create new and diffrent
> 
> Yeah new code for tic tac toe using java ryt?

nope

**Comment by 035pratheeksha** [comment]
Then?

> > > > Could you please assign this to me? @PravinPadalkar78
> > > 
> > > 
> > > create new and diffrent
> > 
> > 
> > Yeah new code for tic tac toe using java ryt?
> 
> nope

Then?

**Comment by codersalman** [comment]
> Then?
> 
> > > > > Could you please assign this to me? @PravinPadalkar78
> > > > 
> > > > 
> > > > create new and diffrent
> > > 
> > > 
> > > Yeah new code for tic tac toe using java ryt?
> > 
> > 
> > nope
> 
> Then?

anything which you can

**Comment by 035pratheeksha** [comment]
I've added PR of login page,Can you please merge it an add me as contributor for hacktoberfest.

**Comment by KaxitPandya** [comment]
@PravinPadalkar78 @codersalman  Please assign this task to me

**Comment by KaxitPandya** [comment]
@codersalman  Please accept my pull request

**Comment by 035pratheeksha** [comment]
@codersalman 

I've added PR of login page,Can you please merge it an add me as contributor for hacktoberfest.
